apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartbank-backend
  namespace: smartbank
  labels:
    app: smartbank-backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: smartbank-backend

  template:
    metadata:
      labels:
        app: smartbank-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "9090"

    spec:
      containers:
        - name: smartbank-backend
          image: sunilreddy32/smartbank-backend:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 9090

          # 🔥 USE CONFIGMAP (IMPORTANT FIX)
          envFrom:
            - configMapRef:
                name: smartbank-config

          # 🔐 ONLY SENSITIVE VALUES FROM SECRET
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: smartbank-secrets
                  key: SPRING_DATASOURCE_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smartbank-secrets
                  key: SPRING_DATASOURCE_PASSWORD

          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            initialDelaySeconds: 60
            periodSeconds: 30

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            initialDelaySeconds: 45
            periodSeconds: 15
