# NodePort instead of LoadBalancer — works in Minikube
# Access via: minikube service smartbank-frontend-service -n smartbank
apiVersion: v1
kind: Service
metadata:
  name: smartbank-frontend-service
  namespace: smartbank
  labels:
    app: smartbank-frontend
spec:
  type: NodePort
  selector:
    app: smartbank-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
