apiVersion: v1
kind: Secret
metadata:
  name: smartbank-secrets
  namespace: smartbank
type: Opaque
stringData:
  DB_USERNAME: smartbank_user
  DB_PASSWORD: Krithi2109
  MAIL_USERNAME: sunilchinnabianagari@gmail.com
  MAIL_PASSWORD: "uwdc eqlc ehzr xqlx"
