# ─────────────────────────────────────────────────────────────
# Kubernetes Secrets — stores sensitive values securely
# These are base64 encoded (NOT encrypted — use AWS Secrets
# Manager in production for stronger security)
#
# To encode a value:
#   echo -n "your-value" | base64
#
# To decode:
#   echo "encoded" | base64 --decode
# ─────────────────────────────────────────────────────────────

apiVersion: v1
kind: Secret
metadata:
  name: smartbank-secrets
  namespace: smartbank
type: Opaque
stringData:
  # stringData allows plain text — Kubernetes encodes automatically
  DB_USERNAME: smartbank_user
  DB_PASSWORD: Krithi@2109 # ← change this
  MAIL_USERNAME: sunilchinnabianagari@gmail.com # ← change this
  MAIL_PASSWORD: uwdc eqlc ehzr xqlx # ← change this
